#!/bin/bash
core() {
  while [ $pokus -lt $5 ]; do
    let pokus=pokus+1
    echo "Pokus č. $pokus"
    let prvaCislica=0;
    let druhaCislica=0;
    let tretiaCislica=0;
    let stvrtaCislica=0;
    read -n1 -e -p "$nick zadajte prvú číslicu: " prvaCislica
    read -n1 -e -p "$nick zadajte druhú číslicu: " druhaCislica
    read -n1 -e -p "$nick zadajte tretiu číslicu: " tretiaCislica
    read -n1 -e -p "$nick zadajte štvrtu číslicu: " stvrtaCislica
    if [ ${#prvaCislica} -eq 0 ]; then
        let prvaCislica=0;
    fi
    if [ ${#druhaCislica} -eq 0 ]; then
        let druhaCislica=0;
    fi
    if [ ${#tretiaCislica} -eq 0 ]; then
        let tretiaCislica=0;
    fi
    if [ ${#stvrtaCislica} -eq 0 ]; then
        let stvrtaCislica=0;
    fi

    echo "Zadana postupnosť $prvaCislica $druhaCislica $tretiaCislica $stvrtaCislica"
    let trafene=0;

    if [ $prvaCislica -eq $1 ]; then
        let trafene=trafene+1;
    fi
    if [ $druhaCislica -eq $2 ]; then
        let trafene=trafene+1;
    fi
    if [ $tretiaCislica -eq $3 ]; then
        let trafene=trafene+1;
    fi
    if [ $stvrtaCislica -eq $4 ]; then
        let trafene=trafene+1;
    fi

    if [ $trafene -eq 4 ]; then
        echo ""
        echo ""
        echo "<<<< GRATUÁLCIA >>>>"
        echo "Bomba úspešne odistená na $pokus pokusov!"
        echo "Hladaná kombinácia: $1 $2 $3 $4"
        echo "$nick ON $6! I SALUTE YOUD"
        exit 0;
    fi

    echo "$nick zlý pokus"
    echo "počet trafených cifier: $trafene"
    echo ""

    echo ""
    echo ""
    echo "$1 $2 $3 $4"
  done


}


echo "*** Vitaj v hre zneškodni bombu ***"
echo ""
echo "Vašou úlohou bude zneškodniť bombu zadaním 4 miesteho kódu."
echo "Jednotlive číslice sa zadávajú samostane."
echo "Po zadaní 4 číslic sa vyhodnotí Váš pokus."
echo "Zobrazí sa Vám informácia o tom, koľko číslic Ste uhádli a"
echo "koľko číslic má vyššiu alebo nižšiu hodnotu ako Váš tip."
echo ""
read -p "Zadajte svoj nick: " nick;
echo "$nick zadajte obtiažnosť:"
echo "1. easy - 30 pokusov na uhádnutie"
echo "2. normal - 15 pokusov  na uhádnutie"
echo "3. hard - 5 pokusov na uhádnutie"
echo ""
let obtiaznosti=2; #pokiaľ človek nič nezadal, tak sa zvolí automaticky stredná obtiažnosť
read -t 5 obtiaznosti

let pokus=0;

case $obtiaznosti in
  "e" | "easy" | "1" | "Easy" | "E" | "EASY")
  echo "Zvolená obtiaťnosť easy!"
  core $((RANDOM % 10)) $((RANDOM%10)) $((RANDOM%10)) $((RANDOM%10)) 30 "EASY";
  ;;
  "n" | "normal" | "2" | "Normal" | "N" | "NORMAL")
  echo "Zvolená obtiaťnosť normal!"
  core $((RANDOM % 10)) $((RANDOM%10)) $((RANDOM%10)) $((RANDOM%10)) 15 "NORMAL";
  ;;
  "h" | "hard" | "3" | "Hard" | "H" | "HARD")
  echo "Zvolená obtiaťnosť hard!"
  core $((RANDOM % 10)) $((RANDOM%10)) $((RANDOM%10)) $((RANDOM%10)) 5 "HARD";
  ;;
  *)
    echo "Nesprávna volba, volím normál "
    core $((RANDOM % 10)) $((RANDOM%10)) $((RANDOM%10)) $((RANDOM%10)) 15 "NORMAL";
  ;;
esac
echo ""
exit 0;