#!/bin/bash
core() {
  echo "$1 $2 $3"
}


echo "*** Vitaj v hre zneškodni bombu ***"
echo ""
echo "Vašou úlohou bude zneškodniť bombu zadaním 4 miesteho kódu."
echo "Jednotlive číslice sa zadávajú samostane."
echo "Po zadaní 4 číslic sa vyhodnotí Váš pokus."
echo "Zobrazí sa Vám informácia o tom, koľko číslic Ste uhádli a"
echo "koľko číslic má vyššiu alebo nižšiu hodnotu ako Váš tip."
echo ""
read -p "Zadajte svoj nick: " nick;
echo "$nick zadajte obtiažnosť:"
echo "1. easy - 30 pokusov na uhádnutie"
echo "2. normal - 15 pokusov  na uhádnutie"
echo "3. hard - 5 pokusov na uhádnutie"
echo ""
read obtiaznosti


case $obtiaznosti in
  "e" | "easy" | "1" | "Easy" | "E" | "EASY")
  echo "Zvolená obtiaťnosť easy!"
  core 1+RANDOm%10 1+RANDOm%10 1+RANDOm%10;
  ;;
  "n" | "normal" | "2" | "Normal" | "N" | "NORMAL")
  echo "Zvolená obtiaťnosť normal!"
  core 1+RANDOm%10 1+RANDOm%10 1+RANDOm%10;
  ;;
  "h" | "hard" | "3" | "Hard" | "H" | "HARD")
  echo "Zvolená obtiaťnosť hard!"
  core 1+RANDOm%10 1+RANDOm%10 1+RANDOm%10;
  ;;
  *)
    echo "Nesprávna volba, volím normál "
    core $((1 + RANDOM % 10)) $((1+RANDOM%10)) $((1+RANDOMr%10));
  ;;
esac
echo ""
exit 0;