#!/bin/bash

#Vytvorte  funkciu,  ktorá  vypíše  vizitku  o  používateľovi
# (login,  meno,  priezvisko, domovský  adresár  a  interpreter  príkazov),
# ktorého  login  je  zadaný  ako  vstupný parameter funkcie.

visitka() {
  userTmp=$(cat /etc/passwd | grep $1 )
  echo "login: $(echo $userTmp | cut -d: -f1)"
  echo "meno: $(echo $userTmp | cut -d: -f5 | cut -d " " -f1)"
  echo "priezvisko: $(echo $userTmp | cut -d: -f5 | cut -d " " -f2)"
  echo "domovy adresar: $(echo $userTmp | cut -d: -f6)"
  echo "interpreter prikazov: $(echo $userTmp | cut -d: -f7)"
}

visitka $1