#!/bin/bash

#Vytvorte  funkciu,  ktorá  pre  rok  zadaný  ako  vstupný  parameter  funkcie  vypíše informáciu, či je daný rok priestupný alebo nie.
priestupny() {
  if [ $(($1 % 4)) == "0" ]; then
    if [ $(($1 % 100)) == "0" ] && [  $(($1 % 400)) == "0" ]; then
      echo "$1 je priestupny!"
      return;
    elif [ $(($1 % 100)) == "0" ]; then
       echo "$1 nie je priestupny!"
       return;
    fi
    echo "$1 je priestupny!"
  else
    echo "$1 nie je priestupny!"

  fi

}

priestupny $1

exit 0